### ISSUE TITLE
Atomic increment/decrement with wrap

### ISSUE THREAD

**Issue by trws** [desul/desul#22]
Cuda and RAJA atomic APIs provide an atomic inc/dec with a wrap value.  It's sufficiently useful I think we should add that here rather than implementing it in raja on top of desul primitives.

**Comment by dalg24** [comment]
Is it what you are referring to?
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomicinc
https://github.com/LLNL/RAJA/blob/dffd98b1ca3f4b0f8308fc0a78d1d66252250d47/include/RAJA/pattern/atomic.hpp#L152-L165

**Comment by trws** [comment]
Yup.  The cuda and hip backends already implement this behavior actually, this is what was just coming up in the sycl PR as well.  @JohnHynes has a PR that should go up a bit later today to add it to the generic interface so you can take a look.

**Comment by dalg24** [comment]
Would you assign this issue to him so no-one else goes and implement it?  (I was actually looking into it just now)

**Comment by trws** [comment]
He just started on it and I didn't have him invited on here yet. As soon as he is, I'll make him the assignee here.

**Comment by JohnHynes** [comment]
The current PR is on my fork found here: https://github.com/JohnHynes/desul/pull/2/files

**Comment by JohnHynes** [comment]
Should all be set to go here: https://github.com/desul/desul/pull/26

**Comment by trws** [comment]
Fixed in #26.
