### ISSUE TITLE
Bad name for atomic fetch operations with wrap around semantics

### ISSUE THREAD

**Issue by dalg24** [desul/desul#46]
`atomic_wrapping_fetch_{inc,dec}` is an unfortunate name that gets in the way of efficient use of macros in the HIP and Cuda implementation.

I would like to suggest we rename `atomic_wrapping_fetch_{inc,dec} -> atomic_fetch_<TO BE DETERMINED>_{inc,dec}`

cc @davidbeckingsale @trws @JohnHynes

**Comment by dalg24** [comment]
I updated #45 to reflect Christian's suggestion.  Please voice your opinion/concern here if you don't like the current name.
Also it occurred to me that `atomic_fetch_{add,sub}_mod` would be another option.

**Comment by trws** [comment]
Works for me.  I think add/sub_mod would be a different op with another argument personally.  A useful one, actually, but not this one.

**Comment by nliber** [comment]
I slightly prefer `atomic_fetch_{add,sub}_mod` over `atomic_fetch_{inc,dec}_mod`, as `inc`/`dec` imply `add`/`sub` by `1`.  But it isn't a strong preference, as both naming schemes are used outside of us (I think Microsoft AMP uses `add`/`sub`).

**Comment by trws** [comment]
This is specifically an interface that does add/sub by one, the argument is the bound at which to wrap.

**Comment by dalg24** [comment]
> Works for me. I think add/sub_mod would be a different op with another argument personally. A useful one, actually, but not this one.

Duh.  You are right.  Not sure what I was thinking :)

**Comment by dalg24** [comment]
I updated #45 to use `atomic_fetch_{inc,dec}_mod`.  Please voice your opinion if you do not like the name or want to suggest something else.

**Comment by dalg24** [comment]
#45 was merged
